version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2.6

      - image: cimg/postgres:14.7
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cliunophpunit

    steps:
      - checkout
      - run: cp .env.example .env
      - run: composer install
      - run: vendor/bin/pest

workflows:
  main:
    jobs:
      - build
