name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      # Install Node dependencies
      - name: Install Node dependencies
        run: pnpm install

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      # Install Composer dependencies
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction

      # Run PHP linting
      - name: Run PHP Linting
        run: composer lint
